#!/bin/bash

Name=$(basename $0)
DirName=$(dirname $0)
DockerFilesDir=${DirName}/dockerfiles
TestsDir=${DirName}/tests
SystemsList=${Name}.list
RoleDir=/etc/ansible/roles
Role=${RoleDir}/role_under_test
Tag=validator

function _echo() {
  echo -e "$(date +%d%m%Y-%H:%M:%S) * $1 "
}

function build(){
  typeset system=$1

  _echo "build ${system} in progress..."
  docker build --file=${DockerFilesDir}/${system} --tag=${system}:${Tag} ${DockerFilesDir}
}

function clean(){
  typeset id=$1

  docker stop ${id} 2>/dev/null
  docker rm   ${id} 2>/dev/null
}

function run() {
  typeset system=$1
  typeset test=$2
  typeset run_opts=""
  typeset init=/sbin/init
  
  _echo "*** ${system} - ${test} in progress..."

  container_id=$(mktemp)
  _echo "container_id=${container_id}"

  _echo "${system} - Initialisation and requirements."
  docker run --detach --volume="${PWD}":${Role}:ro ${run_opts} --name="${system}_${Tag}" ${system}:${Tag} "${init}" > "${container_id}"
  docker exec "$(cat ${container_id})" python ${Role}/requirements.py ${Role}

  _echo "${system} - Ansible syntax check."
  docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${Role}/tests/${test} --syntax-check

  _echo "${system} - Test role."
  docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${Role}/tests/${test} --verbose

  _echo "${system} - Test role idempotence."
  idempotence=$(mktemp)
  docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${Role}/tests/${test} --verbose | tee -a ${idempotence}

  tail ${idempotence} \
  | grep -q 'changed=0.*failed=0' \
  && (echo 'Idempotence test: pass' && exit 0) \
  || (echo 'Idempotence test: fail' && exit 1)

  _echo "*** ${system} - ${test} done."
  _echo "container_id=${container_id}: $(cat ${container_id})"
  docker stop $(cat ${container_id}) && docker rm $(cat ${container_id})
}

### MAIN ###

if [ ! -s ${SystemsList} ] ; then
  ls -1 ${DockerFilesDir} > ${SystemsList}
fi

_echo "Checking tests..."
if [ ! -d ${TestsDir} ] ; then
  mkdir tests
fi
files=(${TestsDir}/*)
if [ ! ${#files[@]} -gt 0 ]; then
  cp defaults/test.yml tests/
fi

cat ${SystemsList} | \
while read system
do
  clean ${system}_${Tag}
  build ${system}
  for test in $(ls -1 tests/)
  do
    run ${system} ${test}
  done
done
